
#cloud-config
users:
  - name: root
    groups: users, admin
    lock_passwd: false
    hashed_passwd: "$6$rounds=500000$YTETrUVvMmEFRUMG$Ioc7.t6cnxuW8NekY231yROkZTYDykJ83J/BifgJyzl3czOL1wMniXYg1gFSN/aOT4nPMgRoGGH7qvXRGCEJS/"
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC2np5I4IARUn0W2Z/+LCXBlxDVGWldSibGn/oidLzmzgUF2vFk6La1r/4yR9tEcV/rr2+WLyogq1wR95oULUg3GkSQSvIsacdXYuqoj41uteAm9eIcNdlNLbqdQGvRSSmsBJ3nZcntDp6idwXY56BHrM5xo454N6MKKXtNWACUGFiRUUC8y7wFCgixEKZu44vM45iwrPAfJRE1eaDAh0bgn440tszfIEvSgGv6wZ+zrqOEsKl8L3/axTLeBU/j4HCXiM69UHHTtwjIRDyApx0ZPIja89CXOskXNVJCX75kAA8qeA9Td/RWmWoxdBL1E1+BIQcf+u8iOkKn3VIwqQeidsKqqhoyEckQmNkkE0kbB91pRFzS9iS4EftEJEmPF2qxQTwz9QvVXz5phEZznUN3QtiAsWUY3ZHg6ug5W/3yGQDyANv1pSEAMWt4omhp2sr5k24q74+Ri+ZULGhiWO0ugkcAOEB+0yzZRRdlkbXByyR+Kp10y+7gCEBdkoNyoVWS4FHNELxPlUxBYsYS10af7I4i4g+DSV2TFs6QDsJd2tdiJZQMvdS3zVQxRjlW3JZ146W17VC0HGLWSARoNADEddIDYDoya1rC3BNuKoLa4gQmXqUpSbCXX26/217NSJuwkM175Qn4EaPA3Rvo9D5uJzna5wSFWlTpf59Wnpq3TQ== mog@Cyberpowerpcmog
      
  - name: devops
    groups: users, admin
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCdWrvnaeK/Yaqdg7q9xnFOgrbmse6XAzs4e1Q1MquHG1fRsSJQxK/QPAs3vuPfWMZEIva+/3w+qtFtHKzz9MafvKK+EN5gvQvHE5bM1FDbibQ3Nm8Dvn3y0IDKLlI3ExgyIHGnH0a9T5T2k/p9AH5bD8fa6cPi1VTEtED80RI7oJKW/lQ7n2KVUrQRWoEJlOfgmaEBdfKHoGJXaDp8xWqnYXAtmm1rstuZDqzLZLrNMFj5YLwafD/B0yPhYtoFo+j5ZOBNWCtIkPFtruTD1Vt0VcMmETe4CDRH7zRIoGc1TkG5pDl681uEUiTJbgK6XQUfdo6eMlVtvalsv4YqneCHFwbFyfWRWGeDk92U+gjLZO9Icp+Oe4dsW9gsLZlAMuJ0swUk+chnQChatFkANV9gWo32fa+16KDl3WkzZOTohu0Bdpj51ZMyIYYiBkqsP7PJXXEVn9jO/2QTD6rYvmtXlelFBB9hSQkgQXuYW7CEM5+TWZxkk+OvDJ01A0fIiGrGwrGujlDqJ6fUAC4ZZyR5plZy5JdoQlvUNnedrhrSKM1spJhJNt07a1iAUvzpIs+/nKCtQ80/cCgY5Ap5UwIUYT8nCcL52doArdL3lDQL7HLqAE8MC1CuYkPE9ug9eLe5+CzZIITrSA/TXANpUcALJ9QXrTadNhECL71YBt5Ggw== ghost@Asteria
      - 
    hashed_passwd: "$6$rounds=500000$TlvHYOnXLTHemxp8$/LBMvNDTElqiN.ARwp.LuJ7Mp8su9w2JIEmS3u9PENVH1PnaZN0ghAz0rPV6NT2nu1kotaD5yen916MqJIHoV."

package_update: true
package_upgrade: true
packages:
  - nginx
  - fail2ban
  - ufw
  - curl
  - tar
  - fuse
runcmd:
  - systemctl enable nginx
  - ufw allow 'Nginx HTTP'
  - printf "[sshd]\nenabled = true\nbanaction = iptables-multiport" > /etc/fail2ban/jail.local
  - systemctl enable fail2ban
  - systemctl start fail2ban
  - ufw allow 'OpenSSH'
  - ufw enable
  - sed -ie '/^PermitRootLogin/s/^.*$/PermitRootLogin yes/' /etc/ssh/sshd_config
  - sed -ie '/^PasswordAuthentication/s/^.*$/PasswordAuthentication yes/' /etc/ssh/sshd_config
  - sed -ie '/^X11Forwarding/s/^.*$/X11Forwarding no/' /etc/ssh/sshd_config
  - sed -ie '/^#MaxAuthTries/s/^.*$/MaxAuthTries 3/' /etc/ssh/sshd_config
  - sed -ie '/^#AllowTcpForwarding/s/^.*$/AllowTcpForwarding no/' /etc/ssh/sshd_config
  - sed -ie '/^#AllowAgentForwarding/s/^.*$/AllowAgentForwarding no/' /etc/ssh/sshd_config
  - sed -i '$a AllowUsers devops root' /etc/ssh/sshd_config
  - systemctl restart ssh
  - rm /var/www/html/*
  - echo "Hello! I am Nginx @ $(curl -s ipinfo.io/ip)! This record added at $(date -u)." >>/var/www/html/index.html
  - mkdir -p ~/.aws && echo -e "[default]\naws_access_key_id = AKID1234567890\naws_secret_access_key = MY-SECRET-KEY" > ~/.aws/credentials
  - curl -O https://storage.googleapis.com/golang/go1.21.5.linux-amd64.tar.gz
  - tar -xvf go1.13.5.linux-amd64.tar.gz
  - mv go /usr/local 
  - ln -s /usr/local/go/bin/go /usr/bin/go
  - echo "export GOPATH=$HOME/work" >> ~/.profile 
  - source ~/.profile
  - go install github.com/kahing/goofys@latest
  - mkdir ~/S3storage
  - echo 'goofys#S3storage /mnt/S3storage fuse _netdev,allow_other,--file-mode=0666,--dir-mode=0777,--endpoint=eu2.contabostorage.com 0 0' | sudo tee -a /etc/fstab 
  - 



